# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27fcb1904021f391b2288cb3acddbf22e7fc21573a8100e3fa7da75a65023a0a6c273d07c64e4a0bada3f65ac290db0af8b004fbcab29fa10871aeef3fc7fda4

test:
  secret_key_base: 41797a3ceb64f0f88782bd233a21fee34cf5b717f400978fd7f8722359d547ba75316a4d3b16ed402773c2e755379b98ad48f0f1742f7582b3e00b071a03fe97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
